name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - psutil
  - ipykernel
  - conda-forge::black
  - conda-forge::rclone
  - conda-forge::hydra-core
  - conda-forge::ipython
  - conda-forge::path.py
  - conda-forge::tqdm
  - pip
  - pip:
    - "black[jupyter]"            # if needed